### ISSUE TITLE
哈哈哈哈哈哈哈哈哈小心被瀹

### ISSUE THREAD

**Issue by bobby285271** [df7c5117/fuckzhxhs#1]
😄😄😄

**Comment by df7c5117** [comment]
刺不刺激（

**Comment by dqwyy** [comment]
噗，被微信续掉了

**Comment by df7c5117** [comment]
本网页因被火爆分享被微信判定为恶意诱导分享，请于浏览器中打开。应该还有部分教师举报。
吹啊吹啊我赤脚不害怕

**Comment by zhangjingye03** [comment]
真有趣，我是不是可以公布执信WiFi密码大全了 :lol:

**Comment by bobby285271** [comment]
@zhangjingye03 二饭有个 TP-LINK_6C2C 密码 123456789 的 Wifi 据说没了？
智慧图书馆和这个的网速都不错，Fantang 那个网速没法忍，至于男生宿舍酒店 Wifi 信号太弱... 所以还是洗洗睡吧
反正双卡，其中一张电信卡每天1块800M绰绰有余（逃

**Comment by bobby285271** [comment]
对了微信可以先扩着这个 http://www.bobby285271.top/fuckzhxhs/
实在不行把仓库丢 fedora people 继续扩...
![screenshot_20170917_172942](https://user-images.githubusercontent.com/20080233/30519701-5397fd5e-9bcf-11e7-818b-5510ba346702.png)

**Comment by df7c5117** [comment]
6c2c还在

我给你们出彩

**Comment by df7c5117** [comment]
不过今天晚上我在学校发现移动4G信号没有上传和下载的流量，是不是已经开始了。。。

**Comment by IGBT460** [comment]
太他妈触了！

**Comment by bobby285271** [comment]
http://mp.weixin.qq.com/s/GvgCD3u7vCuTkpgokQcIOw
吃枣药丸... 迟早要撕起来...😂

**Comment by df7c5117** [comment]
拜读了。整体来说没有说错。我本人对你校的看法是：用一种失格的手段去完成本可以是正当的理由，而且限制网络这个事情对我没有任何大影响。这步棋下得很有水平。总之，这种性质的决策总会被评头论足。权利是靠自己争取来的，所以想要搞事情的人早就要起来搞事情了，与我何干？但是不要揣摩我的核心观点，我的核心观点是没有在这里面体现的。以及，我也没说我的每句话都占理，有些东西纯粹为了娱乐。不过分析得很到位，就是为黑而黑，没有意义，行为艺术。一个在与你校抗争史上意义为0的事件，却被很多人认为是重磅，你可以当真，也可以当笑料，但我觉得当真就没意思了。容易被煽动的固然分分钟被煽动，不能被煽动的……怎么也煽动不起来。所以，怎么看待，全凭个人。
